### PR TITLE
fix local language issue

### LINKED ISSUE #574: on first open for the app, it always takes the arabic language
https://github.com/user-attachments/assets/c62c98ee-f8a2-4440-bf57-2554b4115547

https://github.com/user-attachments/assets/233a35dc-2644-4bf2-b865-7824c8be6707

### PR DESCRIPTION
**Pull request by Al-Qassim**
take device lang and dark theme on first start | take local language and local theme afterword
--- | ---
https://github.com/user-attachments/assets/94283f0e-69c7-4ed4-b72c-adccc9e12d50 | https://github.com/user-attachments/assets/2c476cbf-e762-48e8-a013-0505c49ddc3b

### CODE REVIEW

File: viewmodel/src/main/java/com/cairosquad/viewmodel/main/LocaleViewModel.kt [hunk 1]
```diff
@@ -4,44 +4,37 @@ import androidx.lifecycle.ViewModel
...
         }
 
-        viewModelScope.launch {
-            languageManagerUseCase.getLanguage().collectLatest {
-                _currentLanguage.value = it.toUi()
-            }
-
-        }
-
+//        viewModelScope.launch {
```
Comment (ElsayedMagdy122) [inline viewmodel/src/main/java/com/cairosquad/viewmodel/main/LocaleViewModel.kt]: remove

Comment (Al-Qassim) [reply viewmodel/src/main/java/com/cairosquad/viewmodel/main/LocaleViewModel.kt]: done

**Review by ElsayedMagdy122 — APPROVED** [review]

File: local/src/main/java/com/cairosquad/local/language/LanguageDataSource.kt [hunk 2]
```diff
@@ -32,7 +32,11 @@ class LanguageDataStoreSourceImpl @Inject constructor(
 
     override fun getLanguage(): Flow<String> {
         return dataStore.data.map { preferences ->
-            preferences[LANGUAGE_KEY] ?: getDefaultLanguageBasedOnDevice()
+            preferences[LANGUAGE_KEY]
+                ?: (
+                        getDefaultLanguageBasedOnDevice()
+                            .also { saveLanguage(it) }
+                        )
```
Comment (YoussefmSaber) [inline local/src/main/java/com/cairosquad/local/language/LanguageDataSource.kt:39]: fix the spacing man, press the ctrl + alt + L

**Review by YoussefmSaber — APPROVED** [review]
