### PR TITLE
fix: fix color of tab row

### LINKED ISSUE #395: 115 - Home dividing line is not like the design.
Image

### PR DESCRIPTION
**Pull request by gehadepada**
Closes #395
image
image

### CODE REVIEW

**Review by YoussefmSaber — APPROVED** [review]

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt [hunk 1]
```diff
@@ -7,25 +7,14 @@ import androidx.compose.foundation.background
...
-import androidx.compose.foundation.layout.Arrangement
-import androidx.compose.foundation.layout.Box
-import androidx.compose.foundation.layout.Column
-import androidx.compose.foundation.layout.Row
-import androidx.compose.foundation.layout.fillMaxWidth
-import androidx.compose.foundation.layout.height
-import androidx.compose.foundation.layout.offset
-import androidx.compose.foundation.layout.padding
-import androidx.compose.foundation.layout.width
+import androidx.compose.foundation.layout.*
```
Comment (NadeenXo) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt]: Remove * and import used libraries or functionality only

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt [hunk 2]
```diff
@@ -7,25 +7,14 @@ import androidx.compose.foundation.background
...
 import androidx.compose.foundation.rememberScrollState
 import androidx.compose.material3.Text
-import androidx.compose.runtime.Composable
-import androidx.compose.runtime.getValue
-import androidx.compose.runtime.mutableIntStateOf
-import androidx.compose.runtime.mutableStateMapOf
-import androidx.compose.runtime.remember
-import androidx.compose.runtime.setValue
+import androidx.compose.runtime.*
```
Comment (NadeenXo) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt]: Same

**Review by Al-Qassim — CHANGES_REQUESTED** [review]
the indecator should change to dark gradient when I scroll in the all tab

https://github.com/user-attachments/assets/7dfd6598-2ff5-4743-aae8-83229b66c4d6

https://github.com/user-attachments/assets/3116de7d-c855-440a-ae76-1f84389e6277

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt [hunk 3]
```diff
@@ -131,7 +126,7 @@ fun TabRow(
                     .height(1.dp)
                     .width(indicatorWidth)
                     .align(Alignment.BottomStart)
-                    .background(brush = Theme.color.gradiant.horizontalGradient)
+                    .background(brush = indicatorBrush) // 👈 نستخدم الفرشاة المخصصة هنا
```
Comment (Shahd-Hatem) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt]: Remove comments

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt [hunk 4]
```diff
@@ -141,8 +136,8 @@ fun TabRow(
 @Composable
 private fun TabRowPreview() {
     MovioTheme(isDarkTheme = true) {
-        val tabs = listOf("Top Results", "Movies", "Series", "Artists")
-        var selectedTabIndex by remember { mutableIntStateOf(0) }
+        val tabs = listOf("All", "Movies", "Series", "Categories")
+        var selectedTabIndex by remember { mutableIntStateOf(3) } // جرب "Categories" مباشرة
```
Comment (Shahd-Hatem) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt]: Same

File: design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt [hunk 5]
```diff
@@ -47,6 +47,13 @@ val darkThemeColors = MovioColors(
                 Color(0x33FFFFFF)
             )
         ),
+        horizontalCategoriesGradient = Brush.horizontalGradient(
+            colors = listOf(
+                Color(0x33EBE6FE),
+                Color(0xFFF5F3FF),
```
Comment (Shahd-Hatem) [inline design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt:53]: Can make it at our design system Colors?

Comment (gehadepada) [reply design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt:53]: it already inside the design system

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt [hunk 6]
```diff
@@ -75,6 +62,14 @@ fun TabRow(
         animationSpec = tween(200)
     )
 
+
+    val selectedTabTitle = tabs.getOrNull(selectedTabIndex)
+    val indicatorBrush = if (selectedTabTitle == "Categories") {
```
Comment (ElsayedMagdy122) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt]: what about arabic ? الاصناف 🙂

Comment (gehadepada) [reply design_system/src/main/java/com/cairosquad/design_system/basic_component/TabRow.kt]: yes, you are right

File: ui/src/main/java/com/cairosquad/ui/movio_component/ArtistCard.kt [hunk 7]
```diff
@@ -74,11 +77,32 @@ fun ArtistCard(
...
             style = Theme.textStyle.title.mediumMedium14,
             color = Theme.color.surfaces.onSurface,
             overflow = TextOverflow.Ellipsis,
             maxLines = 1
         )
     }
 }
+@Composable
+@androidx.compose.ui.tooling.preview.Preview(showBackground = true)
+fun ArtistCardPreview_EnglishAndArabic() {
```
Comment (ElsayedMagdy122) [inline ui/src/main/java/com/cairosquad/ui/movio_component/ArtistCard.kt:90]: make it private

**Comment by ElsayedMagdy122** [comment]
@gehadepada  resolve conflicts

File: ui/src/main/java/com/cairosquad/ui/movio_component/ArtistCard.kt (hunk 7 above)
Comment (gehadepada) [reply ui/src/main/java/com/cairosquad/ui/movio_component/ArtistCard.kt:90]: i will handle it at another pr , it not related to this pr sorry

**Review by ElsayedMagdy122 — APPROVED** [review]

**Comment by Al-Qassim** [comment]
another note, in the light mode, the color of the tabs text of "All", "movies" "series" need to be white when no scroll (except categories), when scrolling, it should change to darker color

this in dark mode, all are white
image

this white mode
image

**Comment by gehadepada** [comment]
> another note, in the light mode, the color of the tabs text of "All", "movies" "series" need to be white when no scroll (except categories), when scrolling, it should change to darker color
> 
> this in dark mode, all are white image
> 
> this white mode image

yes i know that , I was going to do it at another pr but no problem i will handle that now

**Review by Al-Qassim — APPROVED** [review]
