### PR TITLE
Fix/fix localization issues

### LINKED ISSUE #403: 30 ,33,34- in arabic there are arabic and english numbers
Image
Image
Image

### PR DESCRIPTION
**Pull request by gehadepada**

### CODE REVIEW

File: viewmodel/src/main/java/com/cairosquad/viewmodel/home/HomeScreenState.kt [hunk 1]
```diff
@@ -40,11 +41,13 @@ data class HomeScreenState(
     data class GenreUiState(
         val id: Long?,
         val name: String,
+        val nameResId: Int? = null
```
Comment (Al-Qassim) [inline viewmodel/src/main/java/com/cairosquad/viewmodel/home/HomeScreenState.kt]: no need to this extra parameter

File: ui/src/main/java/com/cairosquad/ui/see_all_screen/SeeAllScreen.kt [hunk 2]
```diff
@@ -101,7 +101,13 @@ fun SeeAllScreen(
 
             CategoriesChips(
                 modifier = Modifier.padding(top = 16.dp),
-                categories = state.genres.map { it.name },
+                categories = state.genres.map { genre ->
+                    if (genre.nameResId!= null) {
```
Comment (Al-Qassim) [inline ui/src/main/java/com/cairosquad/ui/see_all_screen/SeeAllScreen.kt]: check if `genreId == null`, don't make new attribute `nameResId`

File: viewmodel/src/main/java/com/cairosquad/viewmodel/home/HomeScreenState.kt (hunk 1 above)
Comment (gehadepada) [reply viewmodel/src/main/java/com/cairosquad/viewmodel/home/HomeScreenState.kt]: I want to localize the name of default value ?
What is your idea ?

Comment (gehadepada) [reply viewmodel/src/main/java/com/cairosquad/viewmodel/home/HomeScreenState.kt]: Okay I think I  can at ui check if id =null get name from string resource

**Review by Al-Qassim — APPROVED** [review]

**Comment by ElsayedMagdy122** [comment]
solve conflict

**Review by ElsayedMagdy122 — APPROVED** [review]
