### PR TITLE
fix: bug 56 : issue with cancel search

### LINKED ISSUE #469: 56. I need to press the clear button twice to clear the search input field
https://github.com/user-attachments/assets/11fd2167-182e-4b14-a155-57cfe97c926f

### PR DESCRIPTION
**Pull request by Al-Qassim**

### CODE REVIEW

File: viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt [hunk 1]
```diff
@@ -85,13 +86,15 @@ class SearchViewModel(
     }
 
     override fun onQueryTextChanged(query: String) {
+        Log.d("asdasd", "onQueryTextChanged:  $query")
```
Comment (YoussefmSaber) [inline viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt]: remove the log

**Review by YoussefmSaber — CHANGES_REQUESTED** [review]

File: ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt [hunk 2]
```diff
@@ -75,7 +64,7 @@ fun SearchResultContent(
                 .background(Theme.color.surfaces.surface)
                 .padding(bottom = 12.dp),
             value = state.query,
-            onValueChange = listener::onQueryTextChanged,
+            onValueChange = { },
```
Comment (NadeenXo) [inline ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt:67]: If you pass empty object to all onValueChange then why using it?

Comment (Al-Qassim) [reply ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt:67]: it's not optional parameter, and I don't want to pass any thing, so I left it empty

**Review by NadeenXo — APPROVED** [review]

**Review by ElsayedMagdy122 — APPROVED** [review]

**Review by mohamedibrahim3 — APPROVED** [review]

**Review by YoussefmSaber — APPROVED** [review]
