### PR TITLE
Fix/color of rate numbers at different screens

### LINKED ISSUE #625: Color of rate numbers at seasons screen not correct
https://thechance-workspace.slack.com/archives/C08SY1231RS/p1755267219273749?thread_ts=1755259203.367059&cid=C08SY1231RS

### PR DESCRIPTION
**Pull request by gehadepada**
before 
image
 
after
image

### CODE REVIEW

File: design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt [hunk 1]
```diff
@@ -77,5 +77,9 @@ val darkThemeColors = MovioColors(
                 Color(0xFF080D24)
             )
         )
+    ),
+    warning = Warning(
+        onWarning = Color(0xFFFFFEF9)
```
Comment (NadeenXo) [inline design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt:82]: This already added . you can access it through `Theme.color.system.onWarning`

Comment (gehadepada) [reply design_system/src/main/java/com/cairosquad/design_system/color/darkThemeColors.kt:82]: not same color

**Review by Shahd-Hatem — APPROVED** [review]

**Review by ElsayedMagdy122 — APPROVED** [review]
