### PR TITLE
fix issue login navigation

### LINKED ISSUE #693: issue in login navigation
if we click on login button in the bottom sheet, and we finish the login, we should go back to the same screen we was at, not navigation to the home screen

right now, whenever we go to the login screen, the navigation back stack is cleared, this is not the right behavior

### LINKED ISSUE #694: weird box at app bar
Image

### PR DESCRIPTION
**Pull request by Al-Qassim**
https://github.com/user-attachments/assets/d720a5a4-2447-49c2-b5b6-c4c8d6f9995a

### CODE REVIEW

**Review by Shahd-Hatem — APPROVED** [review]

**Review by AbdelrahmanKarim — APPROVED** [review]

**Review by YoussefmSaber — APPROVED** [review]

File: viewmodel/src/main/java/com/cairosquad/viewmodel/details/movie/MovieViewModel.kt [hunk 1]
```diff
@@ -52,6 +52,27 @@ class MovieViewModel @AssistedInject constructor(
...
+            it.copy(
+                isRateBottomSheetOpen = false,
+                isRatedSuccessBottomSheetOpen = false,
+                isNoAccountBottomSheetOpen = false,
+                isAddToListBottomSheetOpen = false,
+                isShareBottomSheetOpen = false,
+                showCreateListBottomSheet = false,
+            )
+        }
+    }
```
Comment (YoussefmSaber) [inline viewmodel/src/main/java/com/cairosquad/viewmodel/details/movie/MovieViewModel.kt]: extract the content of onSuccess to other function
and put the updateState that at the end in the onEnd block and use for it the call by reference

**Review by ElsayedMagdy122 — APPROVED** [review]
