### PR TITLE
fix/continue as a guest

### LINKED ISSUE #714: issue with opening the app as a guest
when the user opens the app for the first time, and after he finishes the splash screen and the onboarding, he should go to the login screen, no problem until now

when he click on `Continue as a guest` he will go to the home screen, no problem until now

next, if you close the application, then open it, he should go directly to the home screen. this is the right behavior.
right now, if the user is not logged in, and open the app, he will always go to the login screen, regardless of anything, and this is a wrong behavior

### PR DESCRIPTION
**Pull request by Al-Qassim**
https://github.com/user-attachments/assets/7f00fbac-f1da-4b6d-9673-3860e33229ae

### CODE REVIEW

File: viewmodel/src/test/java/com/cairosquad/viewmodel/login/LoginViewModelTest.kt [hunk 1]
```diff
@@ -90,14 +92,14 @@ class LoginViewModelTest {
...
 
-    @Test
-    fun `WHEN continue as guest clicked SHOULD send NavigateToGuestHome effect`() = runTest {
-        viewModel.effect.test {
-            viewModel.onContinueAsAGuestClick()
-            assertThat(awaitItem()).isEqualTo(LoginEffect.NavigateToGuestHome)
-            cancelAndIgnoreRemainingEvents()
-        }
-    }
+//    @Test
```
Comment (NadeenXo) [inline viewmodel/src/test/java/com/cairosquad/viewmodel/login/LoginViewModelTest.kt]: Delete

**Review by NadeenXo — APPROVED** [review]

File: viewmodel/src/test/java/com/cairosquad/viewmodel/home/HomeViewModelTest.kt [hunk 2]
```diff
@@ -160,14 +165,14 @@ class HomeViewModelTest {
...
-        }
-    }
+//    @Test
+//    fun `should emit navigate to profile when onClickProfile called`() = runTest {
+//        viewModel.effect.test {
+//            viewModel.onProfileClick()
+//            assertThat(awaitItem()).isEqualTo(HomeEffect.NavigateToProfile)
+//            cancelAndIgnoreRemainingEvents()
+//        }
+//    }
```
Comment (YoussefmSaber) [inline viewmodel/src/test/java/com/cairosquad/viewmodel/home/HomeViewModelTest.kt]: remove the commented test case

**Review by YoussefmSaber — APPROVED** [review]
