### PR TITLE
fix: rename ObserveAsEvent to ObserveAsEffect

### LINKED ISSUE #164: rename ObserveAsEvent to ObserveAsEffect

### PR DESCRIPTION
**Pull request by yasserahmed10**
rename ObserveAsEvent to ObserveAsEffect

### CODE REVIEW

**Review by gehadepada — APPROVED** [review]

**Review by YoussefmSaber — APPROVED** [review]

File: ui/src/main/java/com/cairosquad/ui/utils/ObserveAsEffect.kt [hunk 1]
```diff
@@ -10,7 +10,7 @@ import kotlinx.coroutines.flow.Flow
 import kotlinx.coroutines.withContext
 
 @Composable
-fun <T> ObserveAsEvent(
+fun <T> ObserveAsEffect(
     events: Flow<T>,
     onEvent: (T) -> Unit,
```
Comment (MostafaMohamed2002) [inline ui/src/main/java/com/cairosquad/ui/utils/ObserveAsEffect.kt:15]: isn't this should be called effects:Flow<T> ?

**Review by MostafaMohamed2002 — COMMENTED** [review]
@yasserahmed10 @YoussefmSaber

File: ui/src/main/java/com/cairosquad/ui/utils/ObserveAsEffect.kt (hunk 1 above)
Comment (yasserahmed10) [reply ui/src/main/java/com/cairosquad/ui/utils/ObserveAsEffect.kt:15]: right
