### PR TITLE
fix :color of tab row at different screens

### LINKED ISSUE #516: fix colors of tab row

### PR DESCRIPTION
**Pull request by gehadepada**
https://github.com/user-attachments/assets/b6ffa7f2-be85-4f4a-b6ba-f80d9eff791b

### CODE REVIEW

File: ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt [hunk 1]
```diff
@@ -145,7 +145,11 @@ private fun TobContent(
             tabs = tabsList.map { stringResource(it) },
             selectedTabIndex = screenState.selectedTab.ordinal,
             onTabSelected = listener::onClickTab,
-            scrollState = scrollState
+            scrollState = scrollState,
+            tabColorWithScroll =  Theme.color.brand.onPrimaryContainer,
```
Comment (MennaSrour) [inline ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: you pass the same colors as parametes put don't fix the issue that Bareq said about this morning as the issue in the colors of tabs in different screens in the light mode

**Review by MennaSrour — CHANGES_REQUESTED** [review]
make sure the problem solved in light theme

File: ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt (hunk 1 above)
Comment (gehadepada) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: are you opened the app?
check video

Comment (MennaSrour) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: image
the color there is not clear and that is exactly what Bareq mention this morning

Comment (gehadepada) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: no colors that at search screen not here

Comment (gehadepada) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: look menna colors at home screen like i made exactly ,when i scroll become darker but at search screen is darker if i scroll or not 
image

image

Comment (gehadepada) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: this screen from bareq review , he at search screen 

image

Comment (MennaSrour) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: yes,I loved what you do in search tabs it is exactly as figma

Comment (MennaSrour) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: image
but see that in figma it is more clear

Comment (gehadepada) [reply ui/src/main/java/com/cairosquad/ui/home/content/HomeScreenContent.kt:149]: thx you menna ,give me beautiful approve like you🌹

**Review by Al-Qassim — APPROVED** [review]
your video have sound

**Review by MennaSrour — APPROVED** [review]
