### PR TITLE
fix: make web view navigate to anything inside tmdb domain

### LINKED ISSUE #536: reset password error says navigation blocked
Image

### PR DESCRIPTION
**Pull request by MennaSrour**

### CODE REVIEW

**Review by YoussefmSaber — APPROVED** [review]

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/WebView.kt [hunk 1]
```diff
@@ -38,22 +38,19 @@ fun WebView(
...
+                    override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
+                        val uri = request.url
+                        val isTmdbDomain = uri.host?.contains("themoviedb.org") == true
 
-                        val isAllowed = isTmdbDomain && (uri.path in allowedPaths)
-
-                        if (!isAllowed) {
-                            Log.d("WebView","Navigation blocked: $url")
+                        return if (isTmdbDomain) {
+                            false // allow
```
Comment (ElsayedMagdy122) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/WebView.kt]: remove comment

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/WebView.kt [hunk 2]
```diff
@@ -38,22 +38,19 @@ fun WebView(
...
+                        } else {
                             Toast.makeText(context, "Navigation blocked", Toast.LENGTH_SHORT).show()
+                            Log.d("WebView", "Navigation blocked: $uri")
```
Comment (ElsayedMagdy122) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/WebView.kt]: remove log and comment

**Review by ElsayedMagdy122 — APPROVED** [review]
