### PR TITLE
fix: rating - bug #2

### LINKED ISSUE #379: 2. The rating should be trimed Ex: (5.3) not (5.368) (edited)
Image

### PR DESCRIPTION
**Pull request by Al-Qassim**
divide the rating by 2 when mapping in the repo, and round to 1st decimal place when mapping in the viewmodel

image

### CODE REVIEW

File: repository/src/main/java/com/cairosquad/repository/movie/data_source/remote/dto/ReviewRemoteDto.kt [hunk 1]
```diff
@@ -27,7 +27,7 @@ data class ReviewRemoteDto(
         id = id,
         author = author.orEmpty(),
         authorPhotoPath = authorDetails?.avatarPath.orEmpty(),
-        rating = authorDetails?.rating ?: 0.0,
+        rating = authorDetails?.rating?.toFloat()?.times(0.5f) ?: 0.0f,
```
Comment (ElsayedMagdy122) [inline repository/src/main/java/com/cairosquad/repository/movie/data_source/remote/dto/ReviewRemoteDto.kt]: why here 0.0 and other places 0

File: repository/src/main/java/com/cairosquad/repository/series/data_source/remote/RemoteDtoMappers.kt [hunk 2]
```diff
@@ -9,7 +9,7 @@ fun SeriesRemoteDto.toEntity(allGenres: List<Genre> = emptyList()): Series {
     return Series(
         id = id ?: 0L,
         title = name ?: "",
-        rating = voteAverage ?: 0f,
+        rating = voteAverage?.times(.5f) ?: 0f,
```
Comment (ElsayedMagdy122) [inline repository/src/main/java/com/cairosquad/repository/series/data_source/remote/RemoteDtoMappers.kt]: why .5 and other places 0.5

File: repository/src/main/java/com/cairosquad/repository/movie/data_source/remote/dto/ReviewRemoteDto.kt (hunk 1 above)
Comment (Al-Qassim) [reply repository/src/main/java/com/cairosquad/repository/movie/data_source/remote/dto/ReviewRemoteDto.kt]: no a problem brother

File: repository/src/main/java/com/cairosquad/repository/series/data_source/remote/RemoteDtoMappers.kt (hunk 2 above)
Comment (Al-Qassim) [reply repository/src/main/java/com/cairosquad/repository/series/data_source/remote/RemoteDtoMappers.kt]: not a problem brother

**Review by ElsayedMagdy122 — APPROVED** [review]

**Review by YoussefmSaber — APPROVED** [review]
