### PR TITLE
fix/image-cache-issue

### LINKED ISSUE #710: coin image cache issue
when there is no internet, the images doesn't render, and they stay empty like this

Image

https://github.com/user-attachments/assets/b74c2229-675e-49e8-b03e-7b2afdea807e

### PR DESCRIPTION
**Pull request by YoussefmSaber**
https://github.com/user-attachments/assets/ccc4a873-6149-4796-b889-04b79cddab7c

### CODE REVIEW

File: safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt [hunk 1]
```diff
@@ -204,13 +210,21 @@ fun SafeImageViewer(
...
+    ) { done ->
         Box(
             modifier = Modifier.fillMaxSize(),
             contentAlignment = Alignment.Center
         ) {
-            if (it) {
-                if (bitmap != null) {
+            when {
+                isError -> {
+                    // Show empty image if an error happened
```
Comment (NadeenXo) [inline safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt]: Delete comments

**Review by Al-Qassim — APPROVED** [review]

File: safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt (hunk 1 above)
Comment (YoussefmSaber) [reply safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt]: done

**Review by NadeenXo — APPROVED** [review]
