### PR TITLE
fix: add error handling

### LINKED ISSUE #413: empty explore section in search screen when no in internet

### PR DESCRIPTION
**Pull request by MennaSrour**

### CODE REVIEW

File: ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt [hunk 1]
```diff
@@ -81,38 +82,52 @@ fun SearchResultContent(
...
+                SearchFailContent(
+                    modifier = modifier,
+                    state = state,
+                    listener = listener
+                )
             }
+        }else {
+            TabRow(
+                modifier = Modifier.padding(bottom = 12.dp),
+                tabs = listOf(
```
Comment (ElsayedMagdy122) [inline ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt:90]: put  remember after tabs equal

**Review by Al-Qassim — CHANGES_REQUESTED** [review]
no error messages appear when I disconnect the internet and make a search

https://github.com/user-attachments/assets/4c73d36e-453b-4da2-9be8-00e698e93d28

File: ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt (hunk 1 above)
Comment (MennaSrour) [reply ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt:90]: can you explain why as i don't understand ?

Comment (Al-Qassim) [reply ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt:90]: put remember, so the list won't be created every time the function recompose
```
tabs = remember { 
                 listOf(
                    stringResource(R.string.top_Results),
                    stringResource(R.string.movies),
                    stringResource(R.string.series),
                    stringResource(R.string.artists),
                )
            }
```

File: viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchInteractionListener.kt [hunk 2]
```diff
@@ -15,4 +15,6 @@ interface SearchInteractionListener {
     fun onArtistClicked(artistId: Long)
     fun onSeeAllForYouClicked()
     fun onTabSelected(index: Int)
+    fun onTabPagingError(error: Throwable?)
```
Comment (Al-Qassim) [inline viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchInteractionListener.kt]: this is not used anywhere, I think you can delete it

image

File: ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt [hunk 3]
```diff
@@ -353,7 +372,47 @@ private fun ArtistsTabContent(
...
+            .verticalScroll(rememberScrollState()),
+        contentAlignment = Alignment.Center
+    ) {
+        StateMessage(
+            imageDrawable = when (errorStatus) {
+                ErrorStatus.NO_INTERNET -> R.drawable.no_internet
+                ErrorStatus.NETWORK_ERROR -> R.drawable.no_result
+                ErrorStatus.UNKNOWN_ERROR -> R.drawable.no_result
+                null -> R.drawable.no_result
+                ErrorStatus.UNAUTHORIZED -> TODO()
```
Comment (Al-Qassim) [inline ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt]: the `TODO()` may cause a crash, put `R.drawable.no_result // TODO`

File: viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt [hunk 4]
```diff
@@ -278,14 +278,20 @@ class SearchViewModel(
...
+    }
 
     private fun setLoading() {
         updateState {
             it.copy(screenStatus = SearchScreenState.ScreenStatus.LOADING)
         }
     }
 
-    private fun handleSearchException(e: Throwable): ErrorStatus {
+    private fun handleSearchException(e: Throwable?): ErrorStatus {
```
Comment (Al-Qassim) [inline viewmodel/src/main/java/com/cairosquad/viewmodel/search/SearchViewModel.kt]: try to not change this to `Throwable?`, try to keep it `Throwable`

**Review by Al-Qassim — APPROVED** [review]

File: ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt (hunk 1 above)
Comment (MennaSrour) [reply ui/src/main/java/com/cairosquad/ui/search/content/SearchResultContent.kt:90]: but i can't use remember with string resourses as it gave me this error:@Composable invocations can only happen from the context of a @Composable function

**Review by ElsayedMagdy122 — APPROVED** [review]
