### PR TITLE
fix: blur threshold

### LINKED ISSUE #72: Issue: Suitable images appear blurred.
Only unsuitable images should be blurred, the female actor's image is currently blurred.

Image

### PR DESCRIPTION
**Pull request by YoussefmSaber**
Changes in this PR: 
- Removed the blur from the Actors images, now you can watch your favorite actor face.
- Adjusted the blur threshold for movie/tv shows posters.

### CODE REVIEW

File: safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt [hunk 1]
```diff
@@ -143,6 +144,7 @@ fun SafeImageViewer(
         ) {
             if (it) {
                 if (bitmap != null) {
+                    Log.d("Moive URL", "SafeImageViewer: $model")
```
Comment (Al-Qassim) [inline safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt]: why there is a log here?

**Review by Al-Qassim — APPROVED** [review]

**Review by MennaSrour — APPROVED** [review]

File: safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt (hunk 1 above)
Comment (YoussefmSaber) [reply safe_image_viewer/src/main/java/com/cairosquad/safe_image_viewer/safe_image_viewer/SafeImageViewer.kt]: It was for debug purpose.
