### PR TITLE
fix: edge to edge problem

### LINKED ISSUE #547: edge to edge handling problem
Image

### PR DESCRIPTION
**Pull request by iZyadNasser**

### CODE REVIEW

File: ui/src/main/java/com/cairosquad/ui/MainActivity.kt [hunk 1]
```diff
@@ -71,8 +71,15 @@ class MainActivity : ComponentActivity() {
             configuration.setLayoutDirection(Locale("en"))
             window.decorView.layoutDirection = View.LAYOUT_DIRECTION_LTR
         }
+        configuration.setLayoutDirection(locale)
 
         @Suppress("DEPRECATION")
```
Comment (ElsayedMagdy122) [inline ui/src/main/java/com/cairosquad/ui/MainActivity.kt:76]: deprecated ?

Comment (iZyadNasser) [reply ui/src/main/java/com/cairosquad/ui/MainActivity.kt:76]: It was used in our code before and approved :), I just followed the commit history until I saw what caused the edge to edge problem and it was removing this line that caused it so I put it back

**Review by Al-Qassim — APPROVED** [review]

**Review by MennaSrour — APPROVED** [review]
