### PR TITLE
fix: rename TopBar to TabRow

### LINKED ISSUE #166: rename TopBar to tabs row, or tabs bar

### PR DESCRIPTION
**Pull request by yasserahmed10**
1. rename TopBar to TabRow

### CODE REVIEW

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabsBar.kt [hunk 1]
```diff
@@ -38,7 +38,7 @@ import androidx.compose.ui.unit.dp
 import com.cairosquad.design_system.theme.MovioTheme
 import com.cairosquad.design_system.theme.Theme
 @Composable
-fun TopBar(
+fun TabsBar(
```
Comment (gehadepada) [inline design_system/src/main/java/com/cairosquad/design_system/basic_component/TabsBar.kt]: rename  it TabRow or TabBar

**Review by YoussefmSaber — CHANGES_REQUESTED** [review]
Change the name to TabRow cause this is the ideal name for it, even material 3 uses this name

**Review by yasserahmed10 — COMMENTED** [review]
@YoussefmSaber 
Done check it again

**Review by gehadepada — APPROVED** [review]

**Review by NadeenXo — APPROVED** [review]

**Review by YoussefmSaber — APPROVED** [review]

File: design_system/src/main/java/com/cairosquad/design_system/basic_component/TabsBar.kt (hunk 1 above)
Comment (yasserahmed10) [reply design_system/src/main/java/com/cairosquad/design_system/basic_component/TabsBar.kt]: done
